// generated by ff-codegen
export const DEV_EXTENSION_BASES = [
  "/@fs/E:/ui designer/packages/ext-demoapp-web",
  "/@fs/E:/ui designer/packages/ext-sample-settings",
  "/@fs/E:/ui designer/packages/ext-assistant",
  "/@fs/E:/ui designer/packages/ext-ui",
  "/@fs/E:/ui designer/packages/ext-compiler",
  "/@fs/E:/ui designer/packages/ext-sandbox",
  "/@fs/E:/ui designer/packages/ext-publish"
] as const;
