// generated by ff-codegen
export const DEV_EXTENSION_BASES = ["/@fs/E:/ui designer/packages/ext-demoapp-web", "\/@fs\/E:\/ui designer\/packages\/ext-sample-settings", "\/@fs\/E:\/ui designer\/packages\/ext-assistant" ] as const;
