#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

// --- args ---
const args = (()=>{
  const out = {};
  const arr = process.argv.slice(2);
  for (let i=0;i<arr.length;i++){
    const tok = arr[i];
    if (tok.startsWith('--')){
      const eq = tok.indexOf('=');
      if (eq !== -1){ out[tok.slice(2,eq)] = tok.slice(eq+1); }
      else {
        const key = tok.slice(2);
        const val = (i+1 < arr.length && !arr[i+1].startsWith('--')) ? arr[++i] : true;
        out[key] = val;
      }
    }
  }
  return out;
})();
const SPEC = args.spec || "builder-output.json";
const TARGET = args.target || "web";        // "web" | "desktop"
const OUTDIR = args.out || "packages/ext-demoapp-web";
const MODE = args.mode || "preview";        // "preview" | "proposal"

// --- helpers ---
const readJSON = p => { let s = fs.readFileSync(p, "utf8"); if (s.charCodeAt(0) === 0xFEFF) s = s.slice(1); return JSON.parse(s); };
const write = (p, s) => { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, s); };
const now = () => new Date().toISOString();

function preview(tree) {
  console.log("Would create:");
  for (const f of tree.files) console.log("  +", f.path);
  console.log("\nWould propose registry entry:");
  console.log("  tools/registry.json :: add", tree.registry.id);
}

function makeWebTree(spec, outdir) {
  const entry = path.join(outdir, "src/entry.tsx");
  const pkg = path.join(outdir, "package.json");
  const manifest = path.join(outdir, "manifest.json");
  const files = [
    { path: entry, body:
`import React from "react";
import type { ExtensionEntry } from "@shared/extension"; // your shared contract
const Main: React.FC = () => <div style={{padding:12}}>${spec.appId} • generated (web)</div>;
export const entry: ExtensionEntry = { mount(ctx){ ctx.openWindow({ title: "${spec.appId}", component: Main }); } };
`
    },
    { path: pkg, body:
`{
  "name": "${spec.extensions[0]?.name || "@frameforge/ext-"+spec.appId+"-web"}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": { "build": "echo \"web build ok\"" }
}
`
    },
    { path: manifest, body:
`{
  "name": "${spec.extensions[0]?.name || "@frameforge/ext-"+spec.appId+"-web"}",
  "id": "${spec.appId}-web",
  "version": "0.1.0",
  "entry": "./src/entry.tsx",
  "permissions": ["propose:spec"],
  "capabilities": { "ui": true }
}
`
    },
  ];
  return { files, registry: { id: spec.appId+"-web", name: spec.extensions[0]?.name || "@frameforge/ext-"+spec.appId+"-web", path: outdir } };
}

function makeDesktopTree(spec, outdir) {
  const entry = path.join(outdir, "src/entry.tsx");
  const pkg = path.join(outdir, "package.json");
  const files = [
    { path: entry, body:
`export function runDesktop() { console.log("${spec.appId}: desktop app entry (stub)"); }`
    },
    { path: pkg, body:
`{
  "name": "${'${spec.extensions[0]?.name || "@frameforge/ext-"+spec.appId+"-desktop"}'}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": { "build": "echo \\\"desktop build ok\\\"" }
}
`
    },
  ];
  return { files, registry: null };
}

function writeTree(tree) {
  for (const f of tree.files) write(f.path, f.body);
}

function writeProposalArtifact(ticketId, patches) {
  const p = `frameforge/reports/proposals/${ticketId}.json`;
  write(p, JSON.stringify({ ticketId, createdAt: now(), patches }, null, 2));
  return p;
}

// Dev auto-loader index used by the OS at boot (Vite /@fs paths)
function updateDevExtensionsIndex(registryEntries) {
  const genPath = "packages/app/src/os/dev-extensions.generated.ts";
  const bases = registryEntries
    .filter(Boolean)
    .map(r => `"/@fs/${path.resolve(r.path).replaceAll("\\","/")}"`)
    .join(", ");
  const body = `// generated by ff-codegen
export const DEV_EXTENSION_BASES = [${bases}] as const;`;
  write(genPath, body);
  return genPath;
}

(function main(){
  const spec = readJSON(SPEC);
  const tree = (TARGET === "desktop")
    ? makeDesktopTree(spec, OUTDIR)
    : makeWebTree(spec, OUTDIR);

  if (MODE === "preview") {
    preview({ ...tree, registry: tree.registry || { id: "(none)" } });
    process.exit(0);
  }

  if (MODE === "proposal") {
    // write files
    writeTree(tree);
    // propose: add to registry (RFC6902) — we emit a patch artifact the Approvals flow can apply
    const patches = [];
    if (tree.registry) {
      // create tools/registry.json if missing
      const regPath = "tools/registry.json";
      if (!fs.existsSync(regPath)) write(regPath, JSON.stringify({ extensions: [] }, null, 2));
      // patch: append entry (approvals system can re-create this mutation)
      patches.push({ op: "add", path: "/tools/registry.json#/extensions/-", value: tree.registry });
    }
    // update dev index so OS boots the extension in dev
    const devIdx = updateDevExtensionsIndex([tree.registry].filter(Boolean));
    const ticketId = crypto.randomUUID();
    const artifact = writeProposalArtifact(ticketId, patches);
    console.log(JSON.stringify({
      ticketId,
      mode: MODE,
      wrote: tree.files.map(f=>f.path).concat(devIdx),
      registryEntry: tree.registry,
      proposalArtifact: artifact
    }, null, 2));
    process.exit(0);
  }

  console.error("Unknown --mode. Use --mode preview | proposal");
  process.exit(1);
})();
