#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';

function parseArgs(argv){
  const args = { target: 'web', spec: null, out: null, mode: 'preview' };
  for (let i=2;i<argv.length;i++){
    const a = argv[i];
    if (a === '--target') args.target = argv[++i] || 'web';
    else if (a === '--spec') args.spec = argv[++i];
    else if (a === '--out') args.out = argv[++i];
    else if (a === '--mode') args.mode = argv[++i];
  }
  if (!args.spec || !args.out) throw new Error('Usage: pnpm ff:codegen --target web|desktop --spec builder-output.json --out packages/ext-<id>');
  return args;
}

async function main(){
  const args = parseArgs(process.argv);
  let raw = await fs.readFile(args.spec, 'utf8');
  if (raw.charCodeAt(0) === 0xFEFF) raw = raw.slice(1);
  const spec = JSON.parse(raw);
  // Inline codegen to avoid TS import; mirrors packages/shared/codegen/generateExtension.ts
  if (spec.version !== 'v1') throw new Error('Unsupported PipelineSpec version');
  const ext = spec.extensions[0];
  const entryPath = 'src/entry.tsx';
  const manifest = {
    name: ext.name,
    version: '0.1.0',
    entry: { module: entryPath },
    capabilities: ['windowApp'],
    permissions: { read: [], propose: [] }
  };
  const entry = `export default function mount(host){ host.openWindow({ title: '${spec.appId}', render: () => '${spec.appId} (${args.target})' }); }\n`;
  const pkg = { name: ext.name, version: '0.1.0', private: true, type: 'module', scripts: { build: args.target === 'desktop' ? "node -e \"console.log('desktop build ok')\"" : "node -e \"console.log('web build ok')\"" } };
  const files = {
    'package.json': JSON.stringify(pkg, null, 2) + '\n',
    'manifest.json': JSON.stringify(manifest, null, 2) + '\n',
    [entryPath]: entry
  };
  const registryEntry = {
    id: spec.appId + (args.target === 'web' ? '_web' : '_desktop'),
    kind: args.target === 'web' ? 'extension' : 'desktop-wrapper',
    endpoint: null,
    status: 'offline',
    lastPingISO: null,
    permissions: { callableBy: ['@frameforge/app'] }
  };

  if (args.mode === 'preview'){
    const preview = {
      outDir: args.out,
      files: Object.entries(files).map(([p,c]) => ({ path: path.join(args.out, p), size: c.length, snippet: String(c).slice(0,120) })),
      registryEntry
    };
    console.log(JSON.stringify(preview, null, 2));
    return;
  }

  if (args.mode === 'proposal'){
    const { Kernel } = await import('../packages/kernel/src/index.mjs');
    const kernel = new Kernel({});
    const diffs = [];
    for (const [rel, content] of Object.entries(files)) {
      diffs.push({ op: 'add', path: `/__file/${args.out}/${rel}`, value: content });
    }
    diffs.push({ op: 'add', path: `/__file/tools/registry.json`, value: { tools: [ registryEntry ] } });
    const ticket = kernel.host.proposals.submit({
      title: `Codegen ${spec.appId} (${args.target})`,
      rationale: 'Generated by ff:codegen (proposal)',
      labels: ['codegen','extension',`app:${spec.appId}`,`target:${args.target}`],
      scope: ['overlays'],
      sourceExtension: '@frameforge/codegen',
      diffs
    });
    console.log(JSON.stringify({ ticketId: ticket.id, diffsCount: diffs.length }, null, 2));
    return;
  }

  throw new Error('Unknown mode. Use --mode preview|proposal');
}

main().catch(err => { console.error(err.stack || err); process.exit(1); });
