export const ERR = {
  GEOMETRY_WRITE_FORBIDDEN: 'GEOMETRY_WRITE_FORBIDDEN',
  PROVENANCE_INCOMPLETE: 'PROVENANCE_INCOMPLETE',
  RBAC_FORBIDDEN: 'RBAC_FORBIDDEN',
  IDEMPOTENCY_DUP: 'IDEMPOTENCY_DUP',
  OVERRIDE_EXPIRED: 'OVERRIDE_EXPIRED',
};

